---
version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: housing_api
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: housing_db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  utils-api:
    container_name: web3-utils
    build: 
      context: .
      dockerfile: utils.Dockerfile
  api:
    container_name: verify-api
    build: .
    image: housing-verify
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      API_ENV: production
      UTILS_HOST: utils-api
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: housing_db
    links:
      - db
    volumes:
      - ./app/:/app
  pgadmin:
    container_name: pgadmin-test
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - 8080:80
volumes:
  db:
    driver: local
